// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcOHVk-rfL-WqNlx_ScxSlfOOdesfhpyA',
    appId: '1:195279116722:web:13ef5473f075200fc36cab',
    messagingSenderId: '195279116722',
    projectId: 'grainguard-1cbcb',
    authDomain: 'grainguard-1cbcb.firebaseapp.com',
    databaseURL: 'https://grainguard-1cbcb-default-rtdb.firebaseio.com',
    storageBucket: 'grainguard-1cbcb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzFmTYw05FGuQjBqg_2Pe003gIb_T0owA',
    appId: '1:195279116722:android:fb3be334ac342a1cc36cab',
    messagingSenderId: '195279116722',
    projectId: 'grainguard-1cbcb',
    databaseURL: 'https://grainguard-1cbcb-default-rtdb.firebaseio.com',
    storageBucket: 'grainguard-1cbcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8H0thD-nk6ijPdWf4en2B1GtKjXKV00',
    appId: '1:195279116722:ios:c99c40ccd72cf331c36cab',
    messagingSenderId: '195279116722',
    projectId: 'grainguard-1cbcb',
    databaseURL: 'https://grainguard-1cbcb-default-rtdb.firebaseio.com',
    storageBucket: 'grainguard-1cbcb.firebasestorage.app',
    iosBundleId: 'com.example.grainguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8H0thD-nk6ijPdWf4en2B1GtKjXKV00',
    appId: '1:195279116722:ios:c99c40ccd72cf331c36cab',
    messagingSenderId: '195279116722',
    projectId: 'grainguard-1cbcb',
    databaseURL: 'https://grainguard-1cbcb-default-rtdb.firebaseio.com',
    storageBucket: 'grainguard-1cbcb.firebasestorage.app',
    iosBundleId: 'com.example.grainguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcOHVk-rfL-WqNlx_ScxSlfOOdesfhpyA',
    appId: '1:195279116722:web:5f9b98a926b22b75c36cab',
    messagingSenderId: '195279116722',
    projectId: 'grainguard-1cbcb',
    authDomain: 'grainguard-1cbcb.firebaseapp.com',
    databaseURL: 'https://grainguard-1cbcb-default-rtdb.firebaseio.com',
    storageBucket: 'grainguard-1cbcb.firebasestorage.app',
  );

}